//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressureRack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PressureRack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться к стойке давления.
        /// </summary>
        internal static string Err1 {
            get {
                return ResourceManager.GetString("Err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уставка больше, чем давление положительного источника.
        /// </summary>
        internal static string Err10 {
            get {
                return ResourceManager.GetString("Err10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уставка меньше, чем давление отрицательного источника.
        /// </summary>
        internal static string Err11 {
            get {
                return ResourceManager.GetString("Err11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя авария стойки давления. Превышен таймаут изменения уставки.
        /// </summary>
        internal static string Err12 {
            get {
                return ResourceManager.GetString("Err12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный номер ошибки (13).
        /// </summary>
        internal static string Err13 {
            get {
                return ResourceManager.GetString("Err13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя авария стойки давления. Потеря связи с прибором переключения каналов пневмосистемы.
        /// </summary>
        internal static string Err14 {
            get {
                return ResourceManager.GetString("Err14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя авария стойки давления. Не удалось установить связь с запрашиваемым контроллером давления из-за системной ошибки СПК.
        /// </summary>
        internal static string Err15 {
            get {
                return ResourceManager.GetString("Err15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя авария стойки давления. Не удалось установить связь с запрашиваемым контроллером давления.
        /// </summary>
        internal static string Err16 {
            get {
                return ResourceManager.GetString("Err16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение прервано.
        /// </summary>
        internal static string Err2 {
            get {
                return ResourceManager.GetString("Err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось расшифровать принятые данные.
        /// </summary>
        internal static string Err3 {
            get {
                return ResourceManager.GetString("Err3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не опознана стойкой давления.
        /// </summary>
        internal static string Err4 {
            get {
                return ResourceManager.GetString("Err4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка изменения уставки при нахождении в очереди.
        /// </summary>
        internal static string Err5 {
            get {
                return ResourceManager.GetString("Err5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос информации о несуществующем канале.
        /// </summary>
        internal static string Err6 {
            get {
                return ResourceManager.GetString("Err6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При изменении уставки задан несуществующий канал.
        /// </summary>
        internal static string Err7 {
            get {
                return ResourceManager.GetString("Err7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При изменении уставки задан канал, на котором находится неактивный контроллер.
        /// </summary>
        internal static string Err8 {
            get {
                return ResourceManager.GetString("Err8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При изменении уставки установлено значение, находящееся за границей диапазона контроллера.
        /// </summary>
        internal static string Err9 {
            get {
                return ResourceManager.GetString("Err9", resourceCulture);
            }
        }
    }
}
