//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressureRack.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PressureRack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось установить связь со стойкой давления. Проверьте, включена ли стойка давления, совпадает ли IP адрес СПК стойки давления и адрес, указанный в настройках.
        /// </summary>
        internal static string Err1 {
            get {
                return ResourceManager.GetString("Err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уставка больше, чем давление положительного источника.
        /// </summary>
        internal static string Err10 {
            get {
                return ResourceManager.GetString("Err10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уставка меньше, чем давление отрицательного источника.
        /// </summary>
        internal static string Err11 {
            get {
                return ResourceManager.GetString("Err11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя авария стойки давления. Превышен таймаут изменения уставки.
        /// </summary>
        internal static string Err12 {
            get {
                return ResourceManager.GetString("Err12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный номер ошибки (13).
        /// </summary>
        internal static string Err13 {
            get {
                return ResourceManager.GetString("Err13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя авария стойки давления. Потеря связи с прибором переключения каналов.
        /// </summary>
        internal static string Err14 {
            get {
                return ResourceManager.GetString("Err14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя авария стойки давления. Не удалось установить связь с запрашиваемым контроллером давления из-за системной ошибки СПК.
        /// </summary>
        internal static string Err15 {
            get {
                return ResourceManager.GetString("Err15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя авария стойки давления. Не удалось установить связь с запрашиваемым контроллером давления.
        /// </summary>
        internal static string Err16 {
            get {
                return ResourceManager.GetString("Err16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение со стойкой давления прервано.
        /// </summary>
        internal static string Err2 {
            get {
                return ResourceManager.GetString("Err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось расшифровать принятые данные.
        /// </summary>
        internal static string Err3 {
            get {
                return ResourceManager.GetString("Err3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не опознана стойкой давления.
        /// </summary>
        internal static string Err4 {
            get {
                return ResourceManager.GetString("Err4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменения уставки при нахождении в очереди.
        /// </summary>
        internal static string Err5 {
            get {
                return ResourceManager.GetString("Err5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос информации о несуществующем канале.
        /// </summary>
        internal static string Err6 {
            get {
                return ResourceManager.GetString("Err6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении уставки задан несуществующий канал.
        /// </summary>
        internal static string Err7 {
            get {
                return ResourceManager.GetString("Err7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении уставки задан канал, на котором находится неактивный контроллер.
        /// </summary>
        internal static string Err8 {
            get {
                return ResourceManager.GetString("Err8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении уставки установлено значение, находящееся за границей диапазона контроллера.
        /// </summary>
        internal static string Err9 {
            get {
                return ResourceManager.GetString("Err9", resourceCulture);
            }
        }
    }
}
